# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  app:
    image: 'dunivivi/travel:latest'
    container_name: app
    depends_on:
      - db
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/travel
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://db:5432/travel
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JHIPSTER_SLEEP=2 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  db:
    image: postgres:14.5
    container_name: db
    # volumes:
    #   - ~/volumes/jhipster/travel/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=travel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5433:5432
